### ISSUE TITLE
extension pulled from chrome store?

### ISSUE THREAD

**Issue by henriklb** [amillman/charcoal#1]
https://chrome.google.com/webstore/detail/charcoal-dark-mode-for-me/aaekanoannlhnajolbijaoflfhikcgng

returns 404, why was this removed?

**Comment by amillman** [comment]
i forgot to update my description and privacy information when asked to, so it got removed. resubmitted and waiting for approval

**Comment by henriklb** [comment]
thank you!

**Comment by amillman** [comment]
its up again, thanks
